### ISSUE TITLE
Check that opened files are being closed correctly

### ISSUE THREAD

**Issue by bojobo** [SamSweere/xmm-epicpn-simulator#2]
Through the code, there are places where files have been opened but not closed correctly (like [here](https://github.com/SamSweere/xmm-epicpn-simulator/blob/b12351e475532dee807fb795ec7ec07e9858dbee/sixte/image_gen.py#L82)).
This can lead to bad behavior (see [here](https://stackoverflow.com/questions/25070854/why-should-i-close-files-in-python)).
Especially if we are opening a lot of files in different processes.

**Comment by SamSweere** [comment]
Yeah, that's a bug
