### ISSUE TITLE
`max_offset` does not exist

### ISSUE THREAD

**Issue by bojobo** [SamSweere/xmm-epicpn-simulator#3]
See [here](https://github.com/SamSweere/xmm-epicpn-simulator/blob/b12351e475532dee807fb795ec7ec07e9858dbee/simput/img_simputgen.py#L23). Should [`maxq_offset`](https://github.com/SamSweere/xmm-epicpn-simulator/blob/b12351e475532dee807fb795ec7ec07e9858dbee/simput/img_simputgen.py#L22) be used?

**Comment by SamSweere** [comment]
Yes, seems like it

**Comment by ivvv** [comment]
I guess it's a typo: `maxq_offset` should be `max_offset`.
